x-logging: &logging
  options:
    max-size: "256k"
    max-file: "1"
  driver: json-file

services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "${LISTEN_IP}:${LISTEN_PORT}:80"
    environment:
      - UI_BASE_URI=$UI_BASE_URI
      - API_BASE_URI=$API_BASE_URI
    logging: *logging

  # ui:
  #   build:
  #     context: ./ui
  #     network: host
  #     args:
  #       - BASE_URI=$UI_BASE_URI
  #   restart: always
  #   logging: *logging
  #   networks:
  #     default:
  #       ipv4_address: "${STATIC_SUBNET}.101"
  #   environment:
  #     - API_BASE_URI=$API_BASE_URI
  #     - LISTEN_PORT=$LISTEN_PORT
  #   volumes:
  #     - ./ui/src:/app/src

  backend:
    build:
      context: ./backend
      network: host
    restart: always
    environment:
      - "LOG_LEVEL=INFO"
      - "API_BASE_URI=$API_BASE_URI"
      - "OPENAI_BASE_URL=$LLM_API_BASE_URL"
      - "OPENAI_API_BASE=$LLM_API_BASE_URL"
      - "OPENAI_API_KEY=$LLM_API_KEY"
      - "LLM_MODEL=$LLM_MODEL"
      - "QDRANT_DB_HOST=qdrant"
      - "LOG_LEVEL=INFO"
    logging: *logging
    networks:
      default:
        ipv4_address: "${STATIC_SUBNET}.102"
    volumes:
      - ./backend/src:/app/src
    ports:
      - "5678:5678" # debugger
    extra_hosts:
      - "host.docker.internal:host-gateway"

  qdrant:
    build:
      context: ./qdrant
    restart: always
    logging: *logging
    ports:
      - "6333:6333" # direct access
    volumes:
      - "qdrant-data:/qdrant/storage:z"

  neo4j:
    build:
      context: ./neo4j
    restart: always
    logging: *logging
    ports:
      - "7474:7474" # direct access
      - "7687:7687" # direct access
    volumes:
      - "neo4j-data:/data:z"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "${STATIC_SUBNET}.0/24"
          gateway: "${STATIC_SUBNET}.1"

volumes:
  qdrant-data:
  neo4j-data:
